In [20]:
import pandas as pd
import numpy as np
import openpyxl

In [21]:
html = pd.read_html('https://work.studentnews.eu/s/3695/75547-European-countries-the-table-language-population-capital-currency-phone-code-internet-code.htm')

In [22]:
countries = html[1].head()
countries

,Staat,Official languages,Population,Capital,Currency,Phone,Int.
0,Austria,German,8.4 million,Vienna,euro (EUR),43,.at
1,Belgium,"Dutch (north), French (south), German",11 million,Brussels,euro (EUR),32,.be
2,Bulgaria,Bulgarian,7 million,Sofia,Bulgarian lev (BGN),359,.bg
3,Croatia,Croatian,4.3 million,Zagreb,Croatian kuna (HRK),385,.hr
4,Cyprus,"Greek, Turkish",800 000,Nicosia,euro (EUR),357,.cy

In [23]:
countries.to_csv('countries.csv',index=False)
countries.to_excel('countries.xlsx', 'Sheet1', index=False)

/var/folders/46/76ys_7h50b9_n3_l1f4m1h8r0000gn/T/ipykernel_40049/1074375295.py:2: FutureWarning: Starting with pandas version 3.0 all arguments of to_excel except for the argument 'excel_writer' will be keyword-only.
  countries.to_excel('countries.xlsx', 'Sheet1', index=False)

ModuleNotFoundError: No module named 'openpyxl'

In [ ]:
top_left = pd.read_csv('top1-25-1.csv')
top_right = pd.read_csv('top1-25-2.csv')
bottom_left = pd.read_csv('top26-50-1.csv')
bottom_right = pd.read_csv('top26-50-2.csv')

In [ ]:
bottom_data = pd.concat([bottom_left, bottom_right], axis = 1)
top_data = pd.merge(top_left, top_right, on= ['Track.Name', 'Popularity'])
data = pd.concat([bottom_data, top_data], sort = False)
data

,Track.Name,Artist.Name,Genre,Beats.Per.Minute,Energy,Danceability,Loudness..dB..,Liveness,Valence.,Length.,Acousticness..,Speechiness.,Popularity
0,If I Can't Have You,Shawn Mendes,canadian pop,124,82,69,-4,13,87,191,49,6,70.0
1,Dance Monkey,Tones and I,australian pop,98,59,82,-6,18,54,210,69,10,83.0
2,It's You,Ali Gatie,canadian hip hop,96,46,73,-7,19,40,213,37,3,89.0
3,Con Calma,Daddy Yankee,latin,94,86,74,-3,6,66,193,11,6,91.0
4,QUE PRETENDES,J Balvin,latin,93,79,64,-4,36,94,222,3,25,89.0
5,Takeaway,The Chainsmokers,edm,85,51,29,-8,10,36,210,12,4,84.0
6,7 rings,Ariana Grande,dance pop,140,32,78,-11,9,33,179,59,33,89.0
7,0.958333333333333,Maluma,reggaeton,96,71,78,-5,9,68,176,22,28,89.0
8,The London (feat. J. Cole & Travis Scott),Young Thug,atl hip hop,98,59,80,-7,13,18,200,2,15,89.0
9,Never Really Over,Katy Perry,dance pop,100,88,77,-5,32,39,224,19,6,89.0
10,Summer Days (feat. Macklemore & Patrick Stump ...,Martin Garrix,big room,114,72,66,-7,14,32,164,18,6,89.0
11,Otro Trago,Sech,panamanian pop,176,70,75,-5,11,62,226,14,34,91.0
12,Antisocial (with Travis Scott),Ed Sheeran,pop,152,82,72,-5,36,91,162,13,5,87.0
13,Sucker,Jonas Brothers,boy band,138,73,84,-5,11,95,181,4,6,80.0
14,"fuck, i'm lonely (with Anne-Marie) - from 13 R...",Lauv,dance pop,95,56,81,-6,6,68,199,48,7,78.0
15,Higher Love,Kygo,edm,104,68,69,-7,10,40,228,2,3,88.0
16,You Need To Calm Down,Taylor Swift,dance pop,85,68,77,-6,7,73,171,1,5,90.0
17,Shallow,Lady Gaga,dance pop,96,39,57,-6,23,32,216,37,3,87.0
18,Talk,Khalid,pop,136,40,90,-9,6,35,198,5,13,84.0
19,Con Altura,ROSALNA,r&b en espanol,98,69,88,-4,5,75,162,39,12,88.0
20,One Thing Right,Marshmello,brostep,88,62,66,-2,58,44,182,7,5,88.0
21,Te Robar,Nicky Jam,latin,176,75,67,-4,8,80,202,24,6,88.0
22,Happier,Marshmello,brostep,100,79,69,-3,17,67,214,19,5,NaN
23,Call You Mine,The Chainsmokers,edm,104,70,59,-6,41,50,218,23,3,88.0
24,Cross Me (feat. Chance the Rapper & PnB Rock),Ed Sheeran,NaN,95,79,75,-6,7,61,206,21,12,82.0
0,Senorita,Shawn Mendes,canadian pop,117,55,76,-6,8,75,191,4,3,79.0
1,China,Anuel AA,reggaeton flow,105,81,79,-4,8,61,302,8,9,92.0
2,boyfriend (with Social House),Ariana Grande,dance pop,190,80,40,-4,16,70,186,12,46,85.0
3,Beautiful People (feat. Khalid),Ed Sheeran,pop,93,65,64,-8,8,55,198,12,19,NaN
4,Goodbyes (Feat. Young Thug),Post Malone,dfw rap,150,65,58,-4,11,18,175,45,7,94.0
5,I Don't Care (with Justin Bieber),Ed Sheeran,pop,102,68,80,-5,9,84,220,9,4,84.0
6,Ransom,Lil Tecca,trap music,180,64,75,-6,7,23,131,2,29,92.0
7,How Do You Sleep?,Sam Smith,pop,111,68,48,-5,8,35,202,15,9,90.0
8,Old Town Road - Remix,Lil Nas X,country rap,136,62,88,-6,11,64,157,5,10,87.0
9,bad guy,Billie Eilish,electropop,135,43,70,-11,10,56,194,33,38,95.0
10,Callaita,Bad Bunny,reggaeton,176,62,61,-5,24,24,251,60,31,93.0
11,Loco Contigo (feat. J. Balvin & Tyga),DJ Snake,dance pop,96,71,82,-4,15,38,185,28,7,86.0
12,Someone You Loved,Lewis Capaldi,pop,110,41,50,-6,11,45,182,75,3,88.0
13,Otro Trago - Remix,Sech,panamanian pop,176,79,73,-2,6,76,288,7,20,87.0
14,Money In The Grave (Drake ft. Rick Ross),Drake,canadian hip hop,101,50,83,-4,12,10,205,10,5,92.0
15,No Guidance (feat. Drake),Chris Brown,dance pop,93,45,70,-7,16,14,261,12,15,82.0
16,LA CANCION,J Balvin,latin,176,65,75,-6,11,43,243,15,32,90.0
17,Sunflower - Spider-Man: Into the Spider-Verse,Post Malone,dfw rap,90,48,76,-6,7,91,158,56,5,91.0
18,Lalala,Y2K,NaN,130,39,84,-8,14,50,161,18,8,88.0
19,Truth Hurts,Lizzo,escape room,158,62,72,-3,12,41,173,11,11,91.0
20,Piece Of Your Heart,MEDUZA,pop house,124,74,68,-7,7,63,153,4,3,91.0
21,Panini,Lil Nas X,country rap,154,59,70,-6,12,48,115,34,8,91.0
22,No Me Conoce - Remix,Jhay Cortez,reggaeton flow,92,79,81,-4,9,58,309,14,7,83.0
23,Soltera - Remix,Lunay,latin,92,78,80,-4,44,80,266,36,4,91.0
24,bad guy (with Justin Bieber),Billie Eilish,electropop,135,45,67,-11,12,68,195,25,30,NaN

In [ ]:
data.head()

,Track.Name,Artist.Name,Genre,Beats.Per.Minute,Energy,Danceability,Loudness..dB..,Liveness,Valence.,Length.,Acousticness..,Speechiness.,Popularity
0,If I Can't Have You,Shawn Mendes,canadian pop,124,82,69,-4,13,87,191,49,6,70.0
1,Dance Monkey,Tones and I,australian pop,98,59,82,-6,18,54,210,69,10,83.0
2,It's You,Ali Gatie,canadian hip hop,96,46,73,-7,19,40,213,37,3,89.0
3,Con Calma,Daddy Yankee,latin,94,86,74,-3,6,66,193,11,6,91.0
4,QUE PRETENDES,J Balvin,latin,93,79,64,-4,36,94,222,3,25,89.0

In [ ]:
data['NR.'] = range(1,51)

data.set_index("NR.",inplace = True)

data

,Track.Name,Artist.Name,Genre,Beats.Per.Minute,Energy,Danceability,Loudness..dB..,Liveness,Valence.,Length.,Acousticness..,Speechiness.,Popularity
NR.,,,,,,,,,,,,,
1,If I Can't Have You,Shawn Mendes,canadian pop,124,82,69,-4,13,87,191,49,6,70.0
2,Dance Monkey,Tones and I,australian pop,98,59,82,-6,18,54,210,69,10,83.0
3,It's You,Ali Gatie,canadian hip hop,96,46,73,-7,19,40,213,37,3,89.0
4,Con Calma,Daddy Yankee,latin,94,86,74,-3,6,66,193,11,6,91.0
5,QUE PRETENDES,J Balvin,latin,93,79,64,-4,36,94,222,3,25,89.0
6,Takeaway,The Chainsmokers,edm,85,51,29,-8,10,36,210,12,4,84.0
7,7 rings,Ariana Grande,dance pop,140,32,78,-11,9,33,179,59,33,89.0
8,0.958333333333333,Maluma,reggaeton,96,71,78,-5,9,68,176,22,28,89.0
9,The London (feat. J. Cole & Travis Scott),Young Thug,atl hip hop,98,59,80,-7,13,18,200,2,15,89.0
10,Never Really Over,Katy Perry,dance pop,100,88,77,-5,32,39,224,19,6,89.0
11,Summer Days (feat. Macklemore & Patrick Stump ...,Martin Garrix,big room,114,72,66,-7,14,32,164,18,6,89.0
12,Otro Trago,Sech,panamanian pop,176,70,75,-5,11,62,226,14,34,91.0
13,Antisocial (with Travis Scott),Ed Sheeran,pop,152,82,72,-5,36,91,162,13,5,87.0
14,Sucker,Jonas Brothers,boy band,138,73,84,-5,11,95,181,4,6,80.0
15,"fuck, i'm lonely (with Anne-Marie) - from 13 R...",Lauv,dance pop,95,56,81,-6,6,68,199,48,7,78.0
16,Higher Love,Kygo,edm,104,68,69,-7,10,40,228,2,3,88.0
17,You Need To Calm Down,Taylor Swift,dance pop,85,68,77,-6,7,73,171,1,5,90.0
18,Shallow,Lady Gaga,dance pop,96,39,57,-6,23,32,216,37,3,87.0
19,Talk,Khalid,pop,136,40,90,-9,6,35,198,5,13,84.0
20,Con Altura,ROSALNA,r&b en espanol,98,69,88,-4,5,75,162,39,12,88.0
21,One Thing Right,Marshmello,brostep,88,62,66,-2,58,44,182,7,5,88.0
22,Te Robar,Nicky Jam,latin,176,75,67,-4,8,80,202,24,6,88.0
23,Happier,Marshmello,brostep,100,79,69,-3,17,67,214,19,5,NaN
24,Call You Mine,The Chainsmokers,edm,104,70,59,-6,41,50,218,23,3,88.0
25,Cross Me (feat. Chance the Rapper & PnB Rock),Ed Sheeran,NaN,95,79,75,-6,7,61,206,21,12,82.0
26,Senorita,Shawn Mendes,canadian pop,117,55,76,-6,8,75,191,4,3,79.0
27,China,Anuel AA,reggaeton flow,105,81,79,-4,8,61,302,8,9,92.0
28,boyfriend (with Social House),Ariana Grande,dance pop,190,80,40,-4,16,70,186,12,46,85.0
29,Beautiful People (feat. Khalid),Ed Sheeran,pop,93,65,64,-8,8,55,198,12,19,NaN
30,Goodbyes (Feat. Young Thug),Post Malone,dfw rap,150,65,58,-4,11,18,175,45,7,94.0
31,I Don't Care (with Justin Bieber),Ed Sheeran,pop,102,68,80,-5,9,84,220,9,4,84.0
32,Ransom,Lil Tecca,trap music,180,64,75,-6,7,23,131,2,29,92.0
33,How Do You Sleep?,Sam Smith,pop,111,68,48,-5,8,35,202,15,9,90.0
34,Old Town Road - Remix,Lil Nas X,country rap,136,62,88,-6,11,64,157,5,10,87.0
35,bad guy,Billie Eilish,electropop,135,43,70,-11,10,56,194,33,38,95.0
36,Callaita,Bad Bunny,reggaeton,176,62,61,-5,24,24,251,60,31,93.0
37,Loco Contigo (feat. J. Balvin & Tyga),DJ Snake,dance pop,96,71,82,-4,15,38,185,28,7,86.0
38,Someone You Loved,Lewis Capaldi,pop,110,41,50,-6,11,45,182,75,3,88.0
39,Otro Trago - Remix,Sech,panamanian pop,176,79,73,-2,6,76,288,7,20,87.0
40,Money In The Grave (Drake ft. Rick Ross),Drake,canadian hip hop,101,50,83,-4,12,10,205,10,5,92.0
41,No Guidance (feat. Drake),Chris Brown,dance pop,93,45,70,-7,16,14,261,12,15,82.0
42,LA CANCION,J Balvin,latin,176,65,75,-6,11,43,243,15,32,90.0
43,Sunflower - Spider-Man: Into the Spider-Verse,Post Malone,dfw rap,90,48,76,-6,7,91,158,56,5,91.0
44,Lalala,Y2K,NaN,130,39,84,-8,14,50,161,18,8,88.0
45,Truth Hurts,Lizzo,escape room,158,62,72,-3,12,41,173,11,11,91.0
46,Piece Of Your Heart,MEDUZA,pop house,124,74,68,-7,7,63,153,4,3,91.0
47,Panini,Lil Nas X,country rap,154,59,70,-6,12,48,115,34,8,91.0
48,No Me Conoce - Remix,Jhay Cortez,reggaeton flow,92,79,81,-4,9,58,309,14,7,83.0
49,Soltera - Remix,Lunay,latin,92,78,80,-4,44,80,266,36,4,91.0
50,bad guy (with Justin Bieber),Billie Eilish,electropop,135,45,67,-11,12,68,195,25,30,NaN

In [ ]:
genre = data.groupby("Genre")
genre

In [ ]:
genre_counted = genre.count()
genre_counted

,Track.Name,Artist.Name,Beats.Per.Minute,Energy,Danceability,Loudness..dB..,Liveness,Valence.,Length.,Acousticness..,Speechiness.,Popularity
Genre,,,,,,,,,,,,
atl hip hop,1,1,1,1,1,1,1,1,1,1,1,1
australian pop,1,1,1,1,1,1,1,1,1,1,1,1
big room,1,1,1,1,1,1,1,1,1,1,1,1
boy band,1,1,1,1,1,1,1,1,1,1,1,1
brostep,2,2,2,2,2,2,2,2,2,2,2,1
canadian hip hop,2,2,2,2,2,2,2,2,2,2,2,2
canadian pop,2,2,2,2,2,2,2,2,2,2,2,2
country rap,2,2,2,2,2,2,2,2,2,2,2,2
dance pop,8,8,8,8,8,8,8,8,8,8,8,8
dfw rap,2,2,2,2,2,2,2,2,2,2,2,2
edm,3,3,3,3,3,3,3,3,3,3,3,3
electropop,2,2,2,2,2,2,2,2,2,2,2,1
escape room,1,1,1,1,1,1,1,1,1,1,1,1
latin,5,5,5,5,5,5,5,5,5,5,5,5
panamanian pop,2,2,2,2,2,2,2,2,2,2,2,2
pop,6,6,6,6,6,6,6,6,6,6,6,5
pop house,1,1,1,1,1,1,1,1,1,1,1,1
r&b en espanol,1,1,1,1,1,1,1,1,1,1,1,1
reggaeton,2,2,2,2,2,2,2,2,2,2,2,2
reggaeton flow,2,2,2,2,2,2,2,2,2,2,2,2
trap music,1,1,1,1,1,1,1,1,1,1,1,1

In [ ]:
genre_counted[genre_counted['Track.Name'] > 3]

,Track.Name,Artist.Name,Beats.Per.Minute,Energy,Danceability,Loudness..dB..,Liveness,Valence.,Length.,Acousticness..,Speechiness.,Popularity
Genre,,,,,,,,,,,,
dance pop,8,8,8,8,8,8,8,8,8,8,8,8
latin,5,5,5,5,5,5,5,5,5,5,5,5
pop,6,6,6,6,6,6,6,6,6,6,6,5

In [ ]:
most_popular_genre = genre.mean(['Popularity'])
most_popular_genre

,Beats.Per.Minute,Energy,Danceability,Loudness..dB..,Liveness,Valence.,Length.,Acousticness..,Speechiness.,Popularity
Genre,,,,,,,,,,
atl hip hop,98.000000,59.000000,80.000000,-7.000000,13.000000,18.000,200.000000,2.000000,15.000000,89.000000
australian pop,98.000000,59.000000,82.000000,-6.000000,18.000000,54.000,210.000000,69.000000,10.000000,83.000000
big room,114.000000,72.000000,66.000000,-7.000000,14.000000,32.000,164.000000,18.000000,6.000000,89.000000
boy band,138.000000,73.000000,84.000000,-5.000000,11.000000,95.000,181.000000,4.000000,6.000000,80.000000
brostep,94.000000,70.500000,67.500000,-2.500000,37.500000,55.500,198.000000,13.000000,5.000000,88.000000
canadian hip hop,98.500000,48.000000,78.000000,-5.500000,15.500000,25.000,209.000000,23.500000,4.000000,90.500000
canadian pop,120.500000,68.500000,72.500000,-5.000000,10.500000,81.000,191.000000,26.500000,4.500000,74.500000
country rap,145.000000,60.500000,79.000000,-6.000000,11.500000,56.000,136.000000,19.500000,9.000000,89.000000
dance pop,111.875000,59.875000,70.250000,-6.125000,15.500000,45.875,202.625000,27.000000,15.250000,85.750000
dfw rap,120.000000,56.500000,67.000000,-5.000000,9.000000,54.500,166.500000,50.500000,6.000000,92.500000
edm,97.666667,63.000000,52.333333,-7.000000,20.333333,42.000,218.666667,12.333333,3.333333,86.666667
electropop,135.000000,44.000000,68.500000,-11.000000,11.000000,62.000,194.500000,29.000000,34.000000,95.000000
escape room,158.000000,62.000000,72.000000,-3.000000,12.000000,41.000,173.000000,11.000000,11.000000,91.000000
latin,126.200000,76.600000,72.000000,-4.200000,21.000000,72.600,225.200000,17.800000,14.600000,89.800000
panamanian pop,176.000000,74.500000,74.000000,-3.500000,8.500000,69.000,257.000000,10.500000,27.000000,89.000000
pop,117.333333,60.666667,67.333333,-6.333333,13.000000,57.500,193.666667,21.500000,8.833333,86.600000
pop house,124.000000,74.000000,68.000000,-7.000000,7.000000,63.000,153.000000,4.000000,3.000000,91.000000
r&b en espanol,98.000000,69.000000,88.000000,-4.000000,5.000000,75.000,162.000000,39.000000,12.000000,88.000000
reggaeton,136.000000,66.500000,69.500000,-5.000000,16.500000,46.000,213.500000,41.000000,29.500000,91.000000
reggaeton flow,98.500000,80.000000,80.000000,-4.000000,8.500000,59.500,305.500000,11.000000,8.000000,87.500000
trap music,180.000000,64.000000,75.000000,-6.000000,7.000000,23.000,131.000000,2.000000,29.000000,92.000000

In [ ]:
print(most_popular_genre['Popularity'].max(),most_popular_genre['Popularity'].idxmax())
print(most_popular_genre['Popularity'].min(),most_popular_genre['Popularity'].idxmin())

95.0 electropop
74.5 canadian pop

In [ ]:
genre = data.groupby('Genre')

In [ ]:
column = data.columns.tolist()[3:]
zanras = genre[column].mean().idxmax()
info = genre[column].mean().max()
result = pd.DataFrame([column, zanras, info], 
                      ['Indicator', 'Genre', 'Score']).transpose()
result

          Indicator           Genre  Score
0  Beats.Per.Minute      trap music  180.0
1            Energy  reggaeton flow   80.0
2      Danceability  r&b en espanol   88.0
3    Loudness..dB..         brostep   -2.5
4          Liveness         brostep   37.5
5          Valence.        boy band   95.0
6           Length.  reggaeton flow  305.5
7    Acousticness..  australian pop   69.0
8      Speechiness.      electropop   34.0
9        Popularity      electropop   95.0

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 50 entries, 1 to 50
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Track.Name        50 non-null     object
 1   Artist.Name       50 non-null     object
 2   Genre             50 non-null     object
 3   Beats.Per.Minute  50 non-null     int64
 4   Energy            50 non-null     int64
 5   Danceability      50 non-null     int64
 6   Loudness..dB..    50 non-null     int64
 7   Liveness          50 non-null     int64
 8   Valence.          50 non-null     int64
 9   Length.           50 non-null     int64
 10  Acousticness..    50 non-null     int64
 11  Speechiness.      50 non-null     int64
 12  Popularity        47 non-null     float64
dtypes: float64(1), int64(9), object(3)
memory usage: 5.5+ KB

In [ ]:
data[data['Genre'].isnull() | data['Popularity'].isnull()]

,Track.Name,Artist.Name,Genre,Beats.Per.Minute,Energy,Danceability,Loudness..dB..,Liveness,Valence.,Length.,Acousticness..,Speechiness.,Popularity
NR.,,,,,,,,,,,,,
23,Happier,Marshmello,brostep,100,79,69,-3,17,67,214,19,5,NaN
25,Cross Me (feat. Chance the Rapper & PnB Rock),Ed Sheeran,NaN,95,79,75,-6,7,61,206,21,12,82.0
29,Beautiful People (feat. Khalid),Ed Sheeran,pop,93,65,64,-8,8,55,198,12,19,NaN
44,Lalala,Y2K,NaN,130,39,84,-8,14,50,161,18,8,88.0
50,bad guy (with Justin Bieber),Billie Eilish,electropop,135,45,67,-11,12,68,195,25,30,NaN

In [ ]:
data['Genre'] = data['Genre'].fillna('pop')
data

,Track.Name,Artist.Name,Genre,Beats.Per.Minute,Energy,Danceability,Loudness..dB..,Liveness,Valence.,Length.,Acousticness..,Speechiness.,Popularity
0,If I Can't Have You,Shawn Mendes,canadian pop,124,82,69,-4,13,87,191,49,6,70.0
1,Dance Monkey,Tones and I,australian pop,98,59,82,-6,18,54,210,69,10,83.0
2,It's You,Ali Gatie,canadian hip hop,96,46,73,-7,19,40,213,37,3,89.0
3,Con Calma,Daddy Yankee,latin,94,86,74,-3,6,66,193,11,6,91.0
4,QUE PRETENDES,J Balvin,latin,93,79,64,-4,36,94,222,3,25,89.0
5,Takeaway,The Chainsmokers,edm,85,51,29,-8,10,36,210,12,4,84.0
6,7 rings,Ariana Grande,dance pop,140,32,78,-11,9,33,179,59,33,89.0
7,0.958333333333333,Maluma,reggaeton,96,71,78,-5,9,68,176,22,28,89.0
8,The London (feat. J. Cole & Travis Scott),Young Thug,atl hip hop,98,59,80,-7,13,18,200,2,15,89.0
9,Never Really Over,Katy Perry,dance pop,100,88,77,-5,32,39,224,19,6,89.0
10,Summer Days (feat. Macklemore & Patrick Stump ...,Martin Garrix,big room,114,72,66,-7,14,32,164,18,6,89.0
11,Otro Trago,Sech,panamanian pop,176,70,75,-5,11,62,226,14,34,91.0
12,Antisocial (with Travis Scott),Ed Sheeran,pop,152,82,72,-5,36,91,162,13,5,87.0
13,Sucker,Jonas Brothers,boy band,138,73,84,-5,11,95,181,4,6,80.0
14,"fuck, i'm lonely (with Anne-Marie) - from 13 R...",Lauv,dance pop,95,56,81,-6,6,68,199,48,7,78.0
15,Higher Love,Kygo,edm,104,68,69,-7,10,40,228,2,3,88.0
16,You Need To Calm Down,Taylor Swift,dance pop,85,68,77,-6,7,73,171,1,5,90.0
17,Shallow,Lady Gaga,dance pop,96,39,57,-6,23,32,216,37,3,87.0
18,Talk,Khalid,pop,136,40,90,-9,6,35,198,5,13,84.0
19,Con Altura,ROSALNA,r&b en espanol,98,69,88,-4,5,75,162,39,12,88.0
20,One Thing Right,Marshmello,brostep,88,62,66,-2,58,44,182,7,5,88.0
21,Te Robar,Nicky Jam,latin,176,75,67,-4,8,80,202,24,6,88.0
22,Happier,Marshmello,brostep,100,79,69,-3,17,67,214,19,5,NaN
23,Call You Mine,The Chainsmokers,edm,104,70,59,-6,41,50,218,23,3,88.0
24,Cross Me (feat. Chance the Rapper & PnB Rock),Ed Sheeran,pop,95,79,75,-6,7,61,206,21,12,82.0
0,Senorita,Shawn Mendes,canadian pop,117,55,76,-6,8,75,191,4,3,79.0
1,China,Anuel AA,reggaeton flow,105,81,79,-4,8,61,302,8,9,92.0
2,boyfriend (with Social House),Ariana Grande,dance pop,190,80,40,-4,16,70,186,12,46,85.0
3,Beautiful People (feat. Khalid),Ed Sheeran,pop,93,65,64,-8,8,55,198,12,19,NaN
4,Goodbyes (Feat. Young Thug),Post Malone,dfw rap,150,65,58,-4,11,18,175,45,7,94.0
5,I Don't Care (with Justin Bieber),Ed Sheeran,pop,102,68,80,-5,9,84,220,9,4,84.0
6,Ransom,Lil Tecca,trap music,180,64,75,-6,7,23,131,2,29,92.0
7,How Do You Sleep?,Sam Smith,pop,111,68,48,-5,8,35,202,15,9,90.0
8,Old Town Road - Remix,Lil Nas X,country rap,136,62,88,-6,11,64,157,5,10,87.0
9,bad guy,Billie Eilish,electropop,135,43,70,-11,10,56,194,33,38,95.0
10,Callaita,Bad Bunny,reggaeton,176,62,61,-5,24,24,251,60,31,93.0
11,Loco Contigo (feat. J. Balvin & Tyga),DJ Snake,dance pop,96,71,82,-4,15,38,185,28,7,86.0
12,Someone You Loved,Lewis Capaldi,pop,110,41,50,-6,11,45,182,75,3,88.0
13,Otro Trago - Remix,Sech,panamanian pop,176,79,73,-2,6,76,288,7,20,87.0
14,Money In The Grave (Drake ft. Rick Ross),Drake,canadian hip hop,101,50,83,-4,12,10,205,10,5,92.0
15,No Guidance (feat. Drake),Chris Brown,dance pop,93,45,70,-7,16,14,261,12,15,82.0
16,LA CANCION,J Balvin,latin,176,65,75,-6,11,43,243,15,32,90.0
17,Sunflower - Spider-Man: Into the Spider-Verse,Post Malone,dfw rap,90,48,76,-6,7,91,158,56,5,91.0
18,Lalala,Y2K,pop,130,39,84,-8,14,50,161,18,8,88.0
19,Truth Hurts,Lizzo,escape room,158,62,72,-3,12,41,173,11,11,91.0
20,Piece Of Your Heart,MEDUZA,pop house,124,74,68,-7,7,63,153,4,3,91.0
21,Panini,Lil Nas X,country rap,154,59,70,-6,12,48,115,34,8,91.0
22,No Me Conoce - Remix,Jhay Cortez,reggaeton flow,92,79,81,-4,9,58,309,14,7,83.0
23,Soltera - Remix,Lunay,latin,92,78,80,-4,44,80,266,36,4,91.0
24,bad guy (with Justin Bieber),Billie Eilish,electropop,135,45,67,-11,12,68,195,25,30,NaN

In [ ]:
data['Popularity'] = data['Popularity'].fillna(data['Popularity'].mean())
data

,Track.Name,Artist.Name,Genre,Beats.Per.Minute,Energy,Danceability,Loudness..dB..,Liveness,Valence.,Length.,Acousticness..,Speechiness.,Popularity
0,If I Can't Have You,Shawn Mendes,canadian pop,124,82,69,-4,13,87,191,49,6,70.000000
1,Dance Monkey,Tones and I,australian pop,98,59,82,-6,18,54,210,69,10,83.000000
2,It's You,Ali Gatie,canadian hip hop,96,46,73,-7,19,40,213,37,3,89.000000
3,Con Calma,Daddy Yankee,latin,94,86,74,-3,6,66,193,11,6,91.000000
4,QUE PRETENDES,J Balvin,latin,93,79,64,-4,36,94,222,3,25,89.000000
5,Takeaway,The Chainsmokers,edm,85,51,29,-8,10,36,210,12,4,84.000000
6,7 rings,Ariana Grande,dance pop,140,32,78,-11,9,33,179,59,33,89.000000
7,0.958333333333333,Maluma,reggaeton,96,71,78,-5,9,68,176,22,28,89.000000
8,The London (feat. J. Cole & Travis Scott),Young Thug,atl hip hop,98,59,80,-7,13,18,200,2,15,89.000000
9,Never Really Over,Katy Perry,dance pop,100,88,77,-5,32,39,224,19,6,89.000000
10,Summer Days (feat. Macklemore & Patrick Stump ...,Martin Garrix,big room,114,72,66,-7,14,32,164,18,6,89.000000
11,Otro Trago,Sech,panamanian pop,176,70,75,-5,11,62,226,14,34,91.000000
12,Antisocial (with Travis Scott),Ed Sheeran,pop,152,82,72,-5,36,91,162,13,5,87.000000
13,Sucker,Jonas Brothers,boy band,138,73,84,-5,11,95,181,4,6,80.000000
14,"fuck, i'm lonely (with Anne-Marie) - from 13 R...",Lauv,dance pop,95,56,81,-6,6,68,199,48,7,78.000000
15,Higher Love,Kygo,edm,104,68,69,-7,10,40,228,2,3,88.000000
16,You Need To Calm Down,Taylor Swift,dance pop,85,68,77,-6,7,73,171,1,5,90.000000
17,Shallow,Lady Gaga,dance pop,96,39,57,-6,23,32,216,37,3,87.000000
18,Talk,Khalid,pop,136,40,90,-9,6,35,198,5,13,84.000000
19,Con Altura,ROSALNA,r&b en espanol,98,69,88,-4,5,75,162,39,12,88.000000
20,One Thing Right,Marshmello,brostep,88,62,66,-2,58,44,182,7,5,88.000000
21,Te Robar,Nicky Jam,latin,176,75,67,-4,8,80,202,24,6,88.000000
22,Happier,Marshmello,brostep,100,79,69,-3,17,67,214,19,5,87.489362
23,Call You Mine,The Chainsmokers,edm,104,70,59,-6,41,50,218,23,3,88.000000
24,Cross Me (feat. Chance the Rapper & PnB Rock),Ed Sheeran,pop,95,79,75,-6,7,61,206,21,12,82.000000
0,Senorita,Shawn Mendes,canadian pop,117,55,76,-6,8,75,191,4,3,79.000000
1,China,Anuel AA,reggaeton flow,105,81,79,-4,8,61,302,8,9,92.000000
2,boyfriend (with Social House),Ariana Grande,dance pop,190,80,40,-4,16,70,186,12,46,85.000000
3,Beautiful People (feat. Khalid),Ed Sheeran,pop,93,65,64,-8,8,55,198,12,19,87.489362
4,Goodbyes (Feat. Young Thug),Post Malone,dfw rap,150,65,58,-4,11,18,175,45,7,94.000000
5,I Don't Care (with Justin Bieber),Ed Sheeran,pop,102,68,80,-5,9,84,220,9,4,84.000000
6,Ransom,Lil Tecca,trap music,180,64,75,-6,7,23,131,2,29,92.000000
7,How Do You Sleep?,Sam Smith,pop,111,68,48,-5,8,35,202,15,9,90.000000
8,Old Town Road - Remix,Lil Nas X,country rap,136,62,88,-6,11,64,157,5,10,87.000000
9,bad guy,Billie Eilish,electropop,135,43,70,-11,10,56,194,33,38,95.000000
10,Callaita,Bad Bunny,reggaeton,176,62,61,-5,24,24,251,60,31,93.000000
11,Loco Contigo (feat. J. Balvin & Tyga),DJ Snake,dance pop,96,71,82,-4,15,38,185,28,7,86.000000
12,Someone You Loved,Lewis Capaldi,pop,110,41,50,-6,11,45,182,75,3,88.000000
13,Otro Trago - Remix,Sech,panamanian pop,176,79,73,-2,6,76,288,7,20,87.000000
14,Money In The Grave (Drake ft. Rick Ross),Drake,canadian hip hop,101,50,83,-4,12,10,205,10,5,92.000000
15,No Guidance (feat. Drake),Chris Brown,dance pop,93,45,70,-7,16,14,261,12,15,82.000000
16,LA CANCION,J Balvin,latin,176,65,75,-6,11,43,243,15,32,90.000000
17,Sunflower - Spider-Man: Into the Spider-Verse,Post Malone,dfw rap,90,48,76,-6,7,91,158,56,5,91.000000
18,Lalala,Y2K,pop,130,39,84,-8,14,50,161,18,8,88.000000
19,Truth Hurts,Lizzo,escape room,158,62,72,-3,12,41,173,11,11,91.000000
20,Piece Of Your Heart,MEDUZA,pop house,124,74,68,-7,7,63,153,4,3,91.000000
21,Panini,Lil Nas X,country rap,154,59,70,-6,12,48,115,34,8,91.000000
22,No Me Conoce - Remix,Jhay Cortez,reggaeton flow,92,79,81,-4,9,58,309,14,7,83.000000
23,Soltera - Remix,Lunay,latin,92,78,80,-4,44,80,266,36,4,91.000000
24,bad guy (with Justin Bieber),Billie Eilish,electropop,135,45,67,-11,12,68,195,25,30,87.489362

In [ ]:
import pandas as pd
import numpy as np

miestas = pd.read_csv('miestai_isvalyti.csv')

miestas.head()

,Miestas,2019,2011,2001,1989,1979,1970,1959,1923,1897
0,Vilnius,540919,535631,542287,576747,475825,370153,236100,167400,154532
1,Kaunas,286763,315993,378650,419745,370000,305600,216850,92446,70920
2,Klaipėda,147898,162360,192954,202929,176648,140342,89500,35845,20100
3,Šiauliai,100119,109328,133883,145629,118724,92375,59700,21387,16128
4,Panevėžys,87148,99690,119749,126483,102303,74497,41100,19197,12968

In [ ]:
miestas.set_index("Miestas", inplace = True)

In [ ]:
miestas

,2019,2011,2001,1989,1979,1970,1959,1923,1897
Miestas,,,,,,,,,
Vilnius,540919,535631,542287,576747,475825,370153,236100,167400,154532
Kaunas,286763,315993,378650,419745,370000,305600,216850,92446,70920
Klaipėda,147898,162360,192954,202929,176648,140342,89500,35845,20100
Šiauliai,100119,109328,133883,145629,118724,92375,59700,21387,16128
Panevėžys,87148,99690,119749,126483,102303,74497,41100,19197,12968
...,...,...,...,...,...,...,...,...,...
Dusetos,560,717,914,1184,1357,1600,1806,1164,1278
Kavarskas,528,666,809,972,1113,1191,1287,1041,1546
Smalininkai,446,515,653,758,805,952,1100,1741,0
Troškūnai,372,451,525,672,1174,1417,1495,1252,1000
Panemunė,210,274,329,398,506,545,539,637,0

In [ ]:
miestas.loc['Marijampolė', '1923']

9488

In [ ]:
miestas[["2019", "1970", "1923"]].head(10)

               2019    1970    1923
Miestas
Vilnius      540919  370153  167400
Kaunas       286763  305600   92446
Klaipėda     147898  140342   35845
Šiauliai     100119   92375   21387
Panevėžys     87148   74497   19197
Alytus        50421   28165    6322
Marijampolė   35253   29073    9488
Mažeikiai     32711   13313    4300
Jonava        26715   14563    4115
Utena         25496   13309    4890

In [ ]:
miestas.shape

(103, 9)

In [ ]:
miestas['nr'] = range(1,104)
miestas

,2019,2011,2001,1989,1979,1970,1959,1923,1897,nr
Miestas,,,,,,,,,,
Vilnius,540919,535631,542287,576747,475825,370153,236100,167400,154532,1
Kaunas,286763,315993,378650,419745,370000,305600,216850,92446,70920,2
Klaipėda,147898,162360,192954,202929,176648,140342,89500,35845,20100,3
Šiauliai,100119,109328,133883,145629,118724,92375,59700,21387,16128,4
Panevėžys,87148,99690,119749,126483,102303,74497,41100,19197,12968,5
...,...,...,...,...,...,...,...,...,...,...
Dusetos,560,717,914,1184,1357,1600,1806,1164,1278,99
Kavarskas,528,666,809,972,1113,1191,1287,1041,1546,100
Smalininkai,446,515,653,758,805,952,1100,1741,0,101
Troškūnai,372,451,525,672,1174,1417,1495,1252,1000,102
Panemunė,210,274,329,398,506,545,539,637,0,103

In [ ]:
miestas[29:39]

                2019   2011   2001   1989   1979   1970  1959  1923  1897  nr
Miestas
Jurbarkas       9831  11232  13797  14310  10644   6541  4422  4409  7400  30
Raseiniai       9784  11203  12541  13211  11403   8946  6200  5270  7455  31
Vilkaviškis     9621  11547  13283  13829  11836   8452  5072  7263  5788  32
Anykščiai       8632  10575  11958  12758  10325   8250  5442  3500  3900  33
Prienai         8516   9867  11353  11909   9398   7550  5423  3260  2477  34
Joniškis        8358   9899  11329  11773   9303   7488  5889  4100  4828  35
Varėna          7987   9240  10845  12291   8015   4478  2401   407  2624  36
Kelmė           7655   9150  10900  11557   9073   6934  5140  2900  3914  37
Kaišiadorys     7486   8664  10002  10964   9022   4618  3011  1929   833  38
Naujoji Akmenė  7266   9300  12345  13590  14195  10127  5400     0     0  39

In [ ]:
miestas[(miestas['nr']>29) & (miestas['nr']<40)]

                2019   2011   2001   1989   1979   1970  1959  1923  1897  nr
Miestas
Jurbarkas       9831  11232  13797  14310  10644   6541  4422  4409  7400  30
Raseiniai       9784  11203  12541  13211  11403   8946  6200  5270  7455  31
Vilkaviškis     9621  11547  13283  13829  11836   8452  5072  7263  5788  32
Anykščiai       8632  10575  11958  12758  10325   8250  5442  3500  3900  33
Prienai         8516   9867  11353  11909   9398   7550  5423  3260  2477  34
Joniškis        8358   9899  11329  11773   9303   7488  5889  4100  4828  35
Varėna          7987   9240  10845  12291   8015   4478  2401   407  2624  36
Kelmė           7655   9150  10900  11557   9073   6934  5140  2900  3914  37
Kaišiadorys     7486   8664  10002  10964   9022   4618  3011  1929   833  38
Naujoji Akmenė  7266   9300  12345  13590  14195  10127  5400     0     0  39

In [ ]:
miestas.drop('nr', axis = 1, inplace=True)

In [ ]:
miestas[miestas['1959'] == 0]

             2019   2011   2001   1989  1979  1970  1959  1923  1897
Miestas
Visaginas   18185  26804  29554  32438  6212     0     0     0     0
Elektrėnai  11276  12012  14050  15871  8466  6730     0     0     0

In [ ]:
miestas[miestas['1897']>miestas['2019']]

                     2019  2011  2001  1989  1979  1970  1959  1923  1897
Miestas
Zarasai              6140  7349  8365  8916  7250  6624  4700  3785  6359
Švenčionys           4139  4980  5684  6469  5284  4617  4006     0  6025
Kalvarija            3858  4457  5090  5701  5879  5622  4698  4529  9378
Eišiškės             3071  3416  3765  3789  3467  3481  2532  2382  3196
Šeduva               2541  2895  3400  3584  3347  3309  3253  3186  4474
Vilkija              1898  2131  2338  2629  2371  2286  1996  2068  2012
Viekšniai            1670  1938  2270  2410  2781  2748  2734  2024  2951
Kudirkos Naumiestis  1480  1732  1997  2061  2090  2486  2574  3067  4595
Žagarė               1366  1712  2312  2649  2918  3386  3800  4730  8285
Salantai             1360  1615  1942  2431  2086  2156  2321  1942  2446
Linkuva              1277  1679  1797  2025  1876  1950  2144  1851  2077
Simnas               1269  1514  1980  2313  1625  1716  1661  1549  1642
Veisiejai            1211  1430  1762  2079  1687  1450  1513  1295  1540
Jieznas              1023  1204  1476  1883  1854  1658  1803  1000  1255
Varniai               995  1140  1355  2028  2059  2027  1902     0  2834
Daugai                980  1120  1458  2790  2054  1384  1287  1153  1288
Seda                  953  1138  1309  1500  1679  1821  2133  1851  2062
Virbalis              885  1095  1351  1566  1635  1489  1429  4018  3293
Vabalninkas           875  1057  1328  1905  2205  2070  2360  1267  2333
Obeliai               847  1074  1371  1804  1648  1681  1907  1328   975
Dūkštas               765   888  1070  1193  1633  1444  1968  1076  1000
Pandėlys              752   809  1024  1167  1129  1184  1277  1000  1221
Užventis              649   833   898  1149  1229  1406  1704     0   945
Dusetos               560   717   914  1184  1357  1600  1806  1164  1278
Kavarskas             528   666   809   972  1113  1191  1287  1041  1546
Troškūnai             372   451   525   672  1174  1417  1495  1252  1000

In [ ]:
miestas[miestas['2019']>miestas['2011']][['2019','2011']]

                2019    2011
Miestas
Vilnius       540919  535631
Šalčininkai     6753    6402
Baltoji Vokė    1052    1047

In [ ]:
decline = miestas[miestas.diff(axis=1, periods=-1) > 0]
select = decline[decline.isna().all(axis=1)]
select
miestas.loc[select.index]

                     2019  2011  2001  1989  1979  1970  1959  1923  1897
Miestas
Kudirkos Naumiestis  1480  1732  1997  2061  2090  2486  2574  3067  4595
Žagarė               1366  1712  2312  2649  2918  3386  3800  4730  8285

In [ ]:
miestas.idxmax()

2019    Vilnius
2011    Vilnius
2001    Vilnius
1989    Vilnius
1979    Vilnius
1970    Vilnius
1959    Vilnius
1923    Vilnius
1897    Vilnius
dtype: object

In [ ]:

procentaliai = ((miestas['2019'] - miestas['1989']) / miestas['1989']) * 100
print(f'{procentaliai.idxmax()}\t {int(procentaliai.max())}%')
print(f'{procentaliai.idxmin()}\t{int(procentaliai.min())}%')

Neringa	 39%
Daugai	-64%

In [ ]:
procentaliai.min()

-64.87455197132617

In [ ]:
miestas.reset_index()

,Miestas,2019,2011,2001,1989,1979,1970,1959,1923,1897
0,Vilnius,540919,535631,542287,576747,475825,370153,236100,167400,154532
1,Kaunas,286763,315993,378650,419745,370000,305600,216850,92446,70920
2,Klaipėda,147898,162360,192954,202929,176648,140342,89500,35845,20100
3,Šiauliai,100119,109328,133883,145629,118724,92375,59700,21387,16128
4,Panevėžys,87148,99690,119749,126483,102303,74497,41100,19197,12968
...,...,...,...,...,...,...,...,...,...,...
98,Dusetos,560,717,914,1184,1357,1600,1806,1164,1278
99,Kavarskas,528,666,809,972,1113,1191,1287,1041,1546
100,Smalininkai,446,515,653,758,805,952,1100,1741,0
101,Troškūnai,372,451,525,672,1174,1417,1495,1252,1000
102,Panemunė,210,274,329,398,506,545,539,637,0